import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.4.21"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven(url = "https://jitpack.io"){
        name="jitpack"
    }
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1")
    //hoplite pour le fichier de config
    implementation ("com.sksamuel.hoplite:hoplite-core:1.3.10")
    implementation ("com.sksamuel.hoplite:hoplite-yaml:1.3.10")

    //GSON
    implementation("com.google.code.gson:gson:2.8.6")

    //log4j
    implementation("org.apache.logging.log4j:log4j-api-kotlin:1.0.0")
    implementation("org.apache.logging.log4j:log4j-api:2.11.1")
    implementation("org.apache.logging.log4j:log4j-core:2.11.1")

    //fuel
    implementation ("com.github.kittinunf.fuel:fuel:2.3.0")
    implementation ("com.github.kittinunf.fuel:fuel-coroutines:2.3.0")
    implementation ("com.github.kittinunf.fuel:fuel-gson:2.3.0")

    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")


}


application {
    // Define the main class for the application.
    mainClassName = "org.isen.CIR3.Paper_News_GGH.AppKt"
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    languageVersion = "1.4"
    jvmTarget = "1.8"

}