/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.isen.CIR3.Paper_News_GGH

import org.apache.logging.log4j.kotlin.logger
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasALogger() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.logger(), "app should have a logger")
    }
}
