
#apiKey: c5362b90a1e54df5a3fc3f381ce21edc
apiKey: 102243dd0279495fa3ad072446e155be
defaultLanguage: fr

categoryList:
  - general
  - sports
  - science
  - technology
  - entertainment
  - business
  - health

countryList:
  - ae
  - ar
  - at
  - au
  - be
  - bg
  - br
  - ca
  - ch
  - cn
  - co
  - cu
  - cz
  - de
  - eg
  - fr
  - gb
  - gr
  - hk
  - hu
  - id
  - ie
  - il
  - in
  - it
  - jp
  - kr
  - lt
  - lv
  - ma
  - mx
  - my
  - ng
  - nl
  - no
  - nz
  - ph
  - pl
  - pt
  - ro
  - rs
  - ru
  - sa
  - se
  - sg
  - si
  - sk
  - th
  - tr
  - tw
  - ua
  - us
  - ve
  - za