/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.isen.CIR3.Paper_News_GGH

import org.apache.logging.log4j.kotlin.Logging
import org.isen.CIR3.Paper_News_GGH.searchEngine.NewsSearchEngine

class App  {
    companion object : Logging
    fun logLaunch(){
        logger.info("Paper_News_GGH Started")
    }
}

fun main(args: Array<String>) {
    App().logLaunch()

    //exemple de recherche qu'on peut imaginer iterer sur les differentes category proposées par le newsAPI
    val test= NewsSearchEngine("gb","business",null)
    for ( e in test.newsResult?.articles!!){
        println(e.title)
    }


}
